// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.emreguru.models;

public interface DealerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dealer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  int getModelCount();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  boolean containsModel(
      int key);
  /**
   * Use {@link #getModelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.emreguru.models.Car>
  getModel();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  java.util.Map<java.lang.Integer, com.emreguru.models.Car>
  getModelMap();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */

  com.emreguru.models.Car getModelOrDefault(
      int key,
      com.emreguru.models.Car defaultValue);
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */

  com.emreguru.models.Car getModelOrThrow(
      int key);
}
