// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credentials.proto

package com.emrek.models;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EmailCredentials emailMode = 1;</code>
   */
  boolean hasEmailMode();
  /**
   * <code>.EmailCredentials emailMode = 1;</code>
   */
  com.emrek.models.EmailCredentials getEmailMode();
  /**
   * <code>.EmailCredentials emailMode = 1;</code>
   */
  com.emrek.models.EmailCredentialsOrBuilder getEmailModeOrBuilder();

  /**
   * <code>.PhoneOTP phoneMode = 2;</code>
   */
  boolean hasPhoneMode();
  /**
   * <code>.PhoneOTP phoneMode = 2;</code>
   */
  com.emrek.models.PhoneOTP getPhoneMode();
  /**
   * <code>.PhoneOTP phoneMode = 2;</code>
   */
  com.emrek.models.PhoneOTPOrBuilder getPhoneModeOrBuilder();

  public com.emrek.models.Credentials.ModeCase getModeCase();
}
