// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.emrek.models;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *1 is a tag that's how the proto file maps the contents 
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *1 is a tag that's how the proto file maps the contents 
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *Primitive int32 type is replaced with proto wrapper
   *wrapper types gives access to message types features
   * </pre>
   *
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  boolean hasAge();
  /**
   * <pre>
   *Primitive int32 type is replaced with proto wrapper
   *wrapper types gives access to message types features
   * </pre>
   *
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  com.google.protobuf.Int32Value getAge();
  /**
   * <pre>
   *Primitive int32 type is replaced with proto wrapper
   *wrapper types gives access to message types features
   * </pre>
   *
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getAgeOrBuilder();

  /**
   * <code>.common.Address address = 3;</code>
   */
  boolean hasAddress();
  /**
   * <code>.common.Address address = 3;</code>
   */
  com.emrek.models.Address getAddress();
  /**
   * <code>.common.Address address = 3;</code>
   */
  com.emrek.models.AddressOrBuilder getAddressOrBuilder();

  /**
   * <pre>
   *Collection of cars can be used
   * </pre>
   *
   * <code>repeated .common.Car car = 4;</code>
   */
  java.util.List<com.emrek.models.Car> 
      getCarList();
  /**
   * <pre>
   *Collection of cars can be used
   * </pre>
   *
   * <code>repeated .common.Car car = 4;</code>
   */
  com.emrek.models.Car getCar(int index);
  /**
   * <pre>
   *Collection of cars can be used
   * </pre>
   *
   * <code>repeated .common.Car car = 4;</code>
   */
  int getCarCount();
  /**
   * <pre>
   *Collection of cars can be used
   * </pre>
   *
   * <code>repeated .common.Car car = 4;</code>
   */
  java.util.List<? extends com.emrek.models.CarOrBuilder> 
      getCarOrBuilderList();
  /**
   * <pre>
   *Collection of cars can be used
   * </pre>
   *
   * <code>repeated .common.Car car = 4;</code>
   */
  com.emrek.models.CarOrBuilder getCarOrBuilder(
      int index);
}
