// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: televison.proto

package com.emrek.models;

public interface TelevisonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Televison)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string brand = 1;</code>
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 1;</code>
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>int32 year = 2;</code>
   */
  int getYear();
}
